### ISSUE TITLE
Trigger words

### ISSUE THREAD

**Issue by researcx** [jrabbit/pyborg-1up#118]
Have a configurable list of trigger words and a configuration option for % chance to reply upon a word being said.
Perhaps do something like how [weechat's highlights](https://weechat.org/files/doc/stable/weechat_user.en.html#option_weechat.look.highlight) work.

This could also change how #26 is done as users could just have bot's nick in the list and optionally put a "(?-i)" before it to make it case sensitive if desired, you could just set the default/example as the bot's nick.

Example:
```toml
# Trigger words
# Put "(?-i)" before a word to make it case sensitive
# Words may begin or end with "*" for partial match
trigger_words = ["(?-i)Pyborg"]
# Chance of reply (%) per trigger word
trigger_reply_chance = 100
```
